upstream eventizer_api {
    server api:3000;
}

upstream eventizer_web {
    server web:4000;
}

upstream eventizer_mailer {
    server mailcatcher:1080;
}

server {
    listen 80;
    server_name localhost;

    location /api/ {
        proxy_pass http://eventizer_api/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /api {
        return 308 /api/;
    }

    location /mailer/ {
        proxy_pass http://eventizer_mailer/;
        proxy_http_version 1.1;

        proxy_set_header Accept-Encoding "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix /mailer;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_redirect / /mailer/;
        sub_filter_once off;
        sub_filter '<base href="/">' '<base href="/mailer/">';
        sub_filter 'src="/assets/' 'src="/mailer/assets/';
        sub_filter 'href="/assets/' 'href="/mailer/assets/';
    }

    location = /mailer {
        return 308 /mailer/;
    }

    location / {
        proxy_pass http://eventizer_web;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
